### ISSUE TITLE
Could not find a file named "pubspec.yaml" when i excute flutter pub get in waterbus

### ISSUE THREAD

**Issue by mohamedegy107** [waterbustech/waterbus#216]
ERROR BODY
Could not find a file named "pubspec.yaml" in https://github.com/waterbustech/flutter-webrtc.git 1ea130539f4612256b04997dc7652fbd7f3ccdbf.

**Comment by lambiengcode** [comment]
- Try to remove `pubspec.lock`:

```bash
rm -rf pubspec.lock
```
- Install Dependencies

on `Android`:
```bash
flutter pub get
```

on `iOS`:

```bash
cd ios
chmod +x clean-pods.sh
./clean-pods.sh
```
