### ISSUE TITLE
Failled to run flutter pub get

### ISSUE THREAD

**Issue by germes96** [waterbustech/waterbus#289]
I have this error when trying to run `flutter pub get`

Resolving dependencies... (18.6s)
Error on line 28, column 11: Invalid description in the "google_sign_in_all_platforms" pubspec on the "google_sign_in_all_platforms_desktop" dependency: "../google_sign_in_all_platforms_desktop" is a relative path, but this isn't a local pubspec.
   ╷
28 │     path: ../google_sign_in_all_platforms_desktop
   │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵

Please how to solve it?

**Comment by lambiengcode** [comment]
It's weird, I tried multiple times and didn't get any errors like that. Could you please try to delete `pubspec.lock` and `pub get` again? And what is flutter version are you using?

**Comment by germes96** [comment]
Thank you. Flutter upgrade solve my issue.
