### ISSUE TITLE
Unresolved reference: SimulcastVideoEncoderFactory

### ISSUE THREAD

**Issue by braysonjohn148** [waterbustech/waterbus#304]
Sorry this is for package: flutter_webrtc_plus since i could not open issue for it.

`While using **flutter_webrtc_plus:0.11.2+3**`
But using older version build the project. **BUT getting a black screen and crash after few seconds** (i think due to logs)
```
package com.cloudwebrtc.webrtc

import android.os.Build
import org.webrtc.EglBase
import org.webrtc.HardwareVideoEncoderFactory
import org.webrtc.SimulcastVideoEncoderFactory
import org.webrtc.SoftwareVideoEncoderFactory
```

```
flutter_webrtc_plus/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt:6:19 Unresolved reference: SimulcastVideoEncoderFactory
flutter_webrtc_plus/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt:246:25 Unresolved reference: SimulcastVideoEncoderFactory
flutter_webrtc_plus/android/src/main/java/com/cloudwebrtc/webrtc/SimulcastVideoEncoderFactoryWrapper.kt:254:18 Unresolved reference: SimulcastVideoEncoderFactory
```

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.1, on macOS 14.5 23F79 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)

**Comment by lambiengcode** [comment]
Thanks for report, I fixed in `flutter_webrtc_plus: 0.11.2+4`
